SamarApp/Areas/Admin/Controllers/AdminsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SamarApp.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SamarApp.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class AdminsController : Controller
    {


        private readonly UserManager<ApplicationUser> _UserManager;

        public AdminsController(UserManager<ApplicationUser> userManager)
        {
            this._UserManager=userManager;
        }


        //public IActionResult Index()
        //{
        //    return View();
        //}

        public async Task<IActionResult> Index(string searchValue)
        {
            if (string.IsNullOrEmpty(searchValue))
            {
                return View(_UserManager.Users);
            }
            else
            {
                var user = await _UserManager.FindByEmailAsync(searchValue);

                return View(new List<ApplicationUser> { user });
            }
        }

        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id == null)
                return NotFound();
            var user = await _UserManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();
            return View(ViewName, user);
        }

        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, ApplicationUser updatedUser)
        {
            if (id != updatedUser.Id)
                return BadRequest();

            if (ModelState.IsValid)
                try
                {
                    var user = await _UserManager.FindByIdAsync(updatedUser.Id);
                   
                    user.UserName = updatedUser.UserName;
                    user.NormalizedUserName = updatedUser.UserName.ToUpper();
                    user.PhoneNumber = updatedUser.PhoneNumber;
                   
                    var result = await _UserManager.UpdateAsync(user);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    throw;
                }

            return View(updatedUser);
        }


        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]

        public async Task<IActionResult> Delete([FromRoute] string id, ApplicationUser DeletedUser)
        {
            if (id != DeletedUser.Id)
                return BadRequest();
            try
            {

                var user = await _UserManager.FindByIdAsync(DeletedUser.Id);
               
                var result = await _UserManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction(nameof(Index));

                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);

                return View(DeletedUser);
            }
            catch (Exception)
            {
                throw;
            }


        }

    }
}

SamarApp/Areas/Admin/Views/Shared/_Athunt.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Personal App</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/Admin/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/Admin/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/Admin/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/Admin/assets/images/favicon.ico" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row flex-grow">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <div class="brand-logo">
                  <img src="~/Admin/assets/images/logo.svg">
                </div>

               
               @RenderBody()

              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/Admin/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/Admin/assets/js/off-canvas.js"></script>
    <script src="~/Admin/assets/js/hoverable-collapse.js"></script>
    <script src="~/Admin/assets/js/misc.js"></script>
      @await RenderSectionAsync("ScriptSection", required: false)
    <!-- endinject -->
  </body>
</html>

SamarApp/Areas/Admin/Views/Shared/_ButtonsPartialVeiw.cshtml
@model string 
<td>
    <a asp-action="Details" asp-controller="Admins" asp-route-id="@Model" class="btn btn-success">
        <i class=" fas fa-eye"></i>Details
    </a>
</td>
<td>
    <a asp-action="Edit" asp-controller="Admins" asp-route-id="@Model" class="btn btn-warning">
        <i class=" fas fa-edit"></i>Edit
    </a>
</td>
<td>
    <a asp-action="Delete" asp-controller="Admins" asp-route-id="@Model" class="btn btn-danger">
        <i class=" fas fa-trash"></i>Delete
    </a>
</td>

SamarApp/Areas/Admin/Views/Shared/_ClientLayout.cshtml
@model SamarApp.Models.SliderViewModel
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  <link rel="apple-touch-icon" sizes="180x180" href="~/src/assets/apple-icon-180x180.png">
  <link href="~/src/assets/favicon.ico" rel="icon">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Admin/assets/css/pdf.css" />
   
  <title>Reseme</title>  


<link href="~/src/style/main.d8e0d294.css" rel="stylesheet"></head>

<body class="" id = "invoice">


    @RenderBody()
    
 <div class="background-color-layer" style="background-image: url('~/src/assets/images/img-01.jpg')"></div>
   <main class="content-wrapper">
  <header class="white-text-container section-container">
     
      
      <!-- Add your content Slider -->

        @foreach (var itemSlider in Model.slider)
   {    

    <div class="text-center">
      <h1>@itemSlider.Name</h1>
      <h3>@itemSlider.JobName</h3>
      <p>
        <a class="fa-icon fa-icon-2x" href="@itemSlider.FacebookLink" title="">
          <i class="fa fa-facebook"></i>
        </a>
        <a class="fa-icon fa-icon-2x" href="@itemSlider.TwitterLink" title="">
          <i class="fa fa-twitter"></i>
        </a>
        <a class="fa-icon fa-icon-2x" href="@itemSlider.LinkedInLink" title="">
          <i class="fa fa-dribbble"></i>
        </a>
        <a class="fa-icon fa-icon-2x" href="@itemSlider.GetHubLink" title="">
          <i class="fa fa-linkedin"></i>
        </a>
      </p>
       </div>
   }
 
  </header>

 <div class="container">
   <div class="row">
     <div class="col-xs-12">




         <!-- About  -->
        <div class="card">
          <div class="card-block">
            <h2>About me</h2>
            @foreach (var item in Model.abouteme)
            {
            <div class="row">
              <div class="col-md-4">
              <p>
                  <img src="@string.Format("/AboutApload/{0}" , item.Image)" class="img-responsive" alt="">
               </p>
              </div>
              <div class="col-md-8">
               <h3>Hello I am @item.Name </h3>
              <p>
                @item.Description
              </p>
              <br />
              <ul class = "left" style = "list-style-type:none;">
               <li ><span><b>Name : </b></span> @item.Name</li>
               <li><span><b>Date of birth : </b></span> @item.DateOfBirth</li> 
               <li><span><b>Nationality : </b> </span> @item.Nationality</li>
               <li><span><b>Work Status :</b></span> @item.WorkStatus</li>
             </ul>
             <ul class = "right" style = "list-style-type:none;">
               <li ><span><b>Phone : </b></span> @item.Phone</li> 
               <li ><span><b>Email : </b></span> @item.Email</li>
               <li  ><span><b>Address : </b></span> @item.Address</li>   
               <li ><span><b>Freelancer : </b></span> @item.Freelancer</li>
            </ul>       
            </div>
            </div>
            }
          </div>
           </div>
     



      <!-- work-experience-->

        <div class="card">
          <div class="card-block">
            <h2>My Works</h2>
            @foreach (var item in Model.work)
            {
            <div class="work-experience">
              <small class="date">@item.StartDate  -  @item.EndDate</small>
              <h3 class="h5 date-title">@item.JobName - <a href="http://en.orson.io" title="Create professionnal website">@item.CompanyName</a></h3>
              <p>
                  @item.Description
              </p>
            </div>
            }
          </div>
        </div>
        



        <!--Education -->
        <div class="card">
          <div class="card-block">
            <h2>Education</h2>
            <div class="row">
                  @foreach (var item in Model.tbEducation)
                 {
                   <div class="col-md-4">
                  <div class="education-experience">
                  <small class="date">@item.QualiDate - @item.QualiEndDate</small>
                  <h3 class="h5 date-title">@item.Qualification</h3>
                  <p>@item.AcademyName</p>
                  </div>
                  </div>             
                 }
          </div>
        </div>
         </div>



        <!-- Language -->
        <div class="card">
          <div class="card-block">
            <h2>Language</h2>
            <div class="row">
                @foreach (var item in Model.tbLanguage)
               {
                <div class="col-md-4">
                <div class="language-experience">
                  <h3 class="h5">@item.LangaugeName <small>@item.Level</small></h3>
                </div>
               </div>  
               }
            </div>
          </div>
        </div>





    

        <!-- Projects-->
        <div class="card">
          <div class="card-block">
            <h2>Projects</h2>
            <div class="row">
                @foreach (var item in Model.tbProjects)
               {
                   <div class="col-md-4">
                  <img src="@string.Format("/ProjectUploads/{0}" , item.PImage)" class="img-responsive" alt="">  
                   <h3 class="h5">@item.Pname</h3>
                   <p>@item.Pdate</p>
                   </div>   
               }  
            </div>
          </div>
        </div>




     </div>
   </div>
 </div>
</main>
<footer class="footer-container white-text-container text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
          <div class="col-md-12 text-right mb-3">
                <button class="btn btn-primary" id="download"> download pdf</button>
            </div>
        <p><img src="~/src/assets/images/mashup-icon.svg" alt=""></p>
        
        <p>©All right reserved. Design <a href="http://www.mashup-template.com/" title="Create website with free html template">Mashup Template</a>/<a href="https://unsplash.com/" title="Beautiful Free Images">Unsplash</a></p>
        <p>
          <a class="fa-icon fa-icon-2x" href="https://facebook.com/" title="">
            <i class="fa fa-facebook"></i>
          </a>
          <a class="fa-icon fa-icon-2x" href="https://twitter.com/" title="">
            <i class="fa fa-twitter"></i>
          </a>
          <a class="fa-icon fa-icon-2x" href="https://dribbble.com/" title="">
            <i class="fa fa-dribbble"></i>
          </a>
          <a class="fa-icon fa-icon-2x" href="https://www.linkedin.com/" title="">
            <i class="fa fa-linkedin"></i>
          </a>
          <a class="fa-icon fa-icon-2x" href="https://vimeo.com/" title="">
            <i class="fa fa-vimeo"></i>
          </a>
        </p>
      </div>
    </div>
  </div>
</footer>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     scrollRevelation('.card');
  });

</script>
<script type="text/javascript" src="~/src/script/main.bc58148c.js"></script></body>
 <script src="~/Admin/assets/js/pdf.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>

</html>


        

SamarApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Personal App</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/Admin/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/Admin/assets/vendors/css/vendor.bundle.base.css">
     <link rel="stylesheet" href="~/Admin/assets/css/Userstyle.css">
   
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/Admin/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/Admin/assets/images/favicon.ico" />
  </head>

  <body>
    <div class="container-scroller">
      <div class="row p-0 m-0 proBanner" id="proBanner">
        <div class="col-md-12 p-0 m-0">
          <div class="card-body card-body-padding d-flex align-items-center justify-content-between">
            <div class="ps-lg-1">
              <div class="d-flex align-items-center justify-content-between">
                <p class="mb-0 font-weight-medium me-3 buy-now-text">Free 24/7 customer support, updates, and more with this template!</p>
                <a href="https://www.bootstrapdash.com/product/purple-bootstrap-admin-template/?utm_source=organic&utm_medium=banner&utm_campaign=buynow_demo" target="_blank" class="btn me-2 buy-now-btn border-0">Get Pro</a>
              </div>
            </div>
            <div class="d-flex align-items-center justify-content-between">
              <a href="https://www.bootstrapdash.com/product/purple-bootstrap-admin-template/"><i class="mdi mdi-home me-3 text-white"></i></a>
              <button id="bannerClose" class="btn border-0 p-0">
                <i class="mdi mdi-close text-white me-0"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          <a class="navbar-brand brand-logo" href="index.html"><img src="~/Admin/assets/images/logo.svg" alt="logo" /></a>
          <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/Admin/assets/images/logo-mini.svg" alt="logo" /></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
          </button>
          <div class="search-field d-none d-md-block">
            <form class="d-flex align-items-center h-100" action="#">
              <div class="input-group">
                <div class="input-group-prepend bg-transparent">
                  <i class="input-group-text border-0 mdi mdi-magnify"></i>
                </div>
                <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
              </div>
            </form>
          </div> 

        
          <ul class="navbar-nav navbar-nav-right">

             <li class="nav-item nav-profile dropdown">
             
              <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                <a class="dropdown-item" asp-controller = "Account" asp-action = "Login">
                  <i class="mdi mdi-cached me-2 text-success"></i> Activity Log </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller = "Account" asp-action = "SignOut">
                  <i class="mdi mdi-logout me-2 text-primary"></i> Signout </a>
              </div>
            </li>   
           
          </ul>        
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
          </button>
         
         
        </div>
   
      </nav>

      
      <!-- partial -->

      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <ul class="nav">

            <li class="nav-item">
              <a class="nav-link" asp-controller = "Home" asp-action = "Index">
                <span class="menu-title">Home</span>
                <i class="mdi mdi-home menu-icon"></i>
              </a>
            </li>


            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#general-pages" aria-expanded="false" aria-controls="general-pages">
                <span class="menu-title">Account Settings</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi-medical-bag menu-icon"></i>
              </a>
              <div class="collapse" id="general-pages">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item"> <a class="nav-link" asp-controller = "Account" asp-action = "Login"> Login </a></li>
                  <li class="nav-item"> <a class="nav-link" asp-controller = "Account" asp-action = "Register"> Register </a></li>
                 <li class="nav-item"> <a class="nav-link" asp-controller = "Account" asp-action = "SignOut"> SignOut </a></li>               
              </ul>
              </div>
            </li>

          
            <li class="nav-item">
              <a class="nav-link" asp-controller = "Slider" asp-action = "MySlider" >
                <span class="menu-title">Create Your Slider</span>
                <i class="mdi mdi-contacts menu-icon"></i>
              </a>
            </li>


            <li class="nav-item">
              <a class="nav-link" asp-controller = "About" asp-action = "AboutInfo">
                <span class="menu-title">Add Your Personal Info</span>
                <i class="mdi mdi-account-circle menu-icon"></i>
              </a>
            </li>


            <li class="nav-item">
              <a class="nav-link" asp-controller = "Work" asp-action = "MyWork">
                <span class="menu-title">Add Your Work</span>
                <i class="mdi mdi-briefcase menu-icon"></i>
              </a>
            </li>


            <li class="nav-item">
              <a class="nav-link" asp-controller = "Education" asp-action = "MyEducation">
                <span class="menu-title">Add Your Education </span>
                <i class="mdi mdi-school menu-icon"></i>
              </a>
            </li>

             <li class="nav-item">
              <a class="nav-link" asp-controller = "Language" asp-action = "MyLanguages">
                <span class="menu-title">Add Your Language </span>
                <i class="mdi mdi-google-translate menu-icon"></i>
              </a>
            </li>


            <li class="nav-item sidebar-actions">
              <span class="nav-link">
                <div class="border-bottom">
                  <h6 class="font-weight-normal mb-3">Projects</h6>
                </div>
                <a asp-controller = "Project" asp-action = "MyProjects"  class="btn btn-block btn-lg btn-gradient-primary mt-4">+ Add a project</a>
              </span>
            </li>


             <li class="nav-item sidebar-actions">
              <span class="nav-link">
                <div class="border-bottom">
                  <h6 class="font-weight-normal mb-3">Your CV</h6>
                </div>
                <a asp-controller = "Home" asp-action = "Client_CV"  class="btn btn-block btn-lg btn-gradient-primary mt-4"> CV</a>
              </span>
            </li>


          </ul>
        </nav>
         <div class="main-panel">
         <div class="content-wrapper">
             <div class = "row">
                    @RenderBody()
       </div>
      </div>
       <footer class="footer">
            <div class="container-fluid d-flex justify-content-between">
              <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © bootstrapdash.com 2021</span>
              <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin template</a> from Bootstrapdash.com</span>
            </div>
          </footer>

      </div>
    </div>
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/Admin/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/Admin/assets/vendors/chart.js/Chart.min.js"></script>
    <script src="~/Admin/assets/js/jquery.cookie.js" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/Admin/assets/js/off-canvas.js"></script>
    <script src="~/Admin/assets/js/hoverable-collapse.js"></script>
    <script src="~/Admin/assets/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/Admin/assets/js/dashboard.js"></script>
    <script src="~/Admin/assets/js/todolist.js"></script>
     <script src="~/Admin/assets/js/app.js"></script>
  
    <!-- End custom js for this page -->
  </body>
</html>